---
run:
  build-tags:
    - apparmor
    - seccomp
    - selinux
    - systemd
    - exclude_graphdriver_btrfs
    - containers_image_openpgp
  concurrency: 6
  deadline: 5m
linters:
  enable:
    - dupl
    - gocritic
    - unparam
    - exportloopref
    - revive
    - prealloc
    - makezero
    - gofumpt
linters-settings:
  errcheck:
    check-type-assertions: true
  gocyclo:
    min-complexity: 35

issues:
    # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - dupl
