name: validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

env:
  LINT_VERSION: v1.53

jobs:
  codespell:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: install deps
      # Version of codespell bundled with Ubuntu is way old, so use pip.
      run: pip install codespell
    - name: run codespell
      run: codespell -L ro,hastable,shouldnot
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - uses: actions/setup-go@v4
      with:
        go-version: 1.19
    - name: install deps
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install libseccomp-dev libdevmapper-dev
    - name: lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: "${{ env.LINT_VERSION }}"
        only-new-issues: true
        args: --verbose
    # Extra linters, only checking new code from a pull request.
    - name: Extra golangci-lint config. switcharoo
      run: mv .golangci-extra.yml golangci.yml
    - name: lint-extra
      uses: golangci/golangci-lint-action@v3
      with:
        version: "${{ env.LINT_VERSION }}"
        only-new-issues: true

    - name: validate seccomp
      run: ./tools/validate_seccomp.sh ./pkg/seccomp
